/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HTTPValidationError,
  WorkerCreate,
  WorkerResponse
} from './fastAPI.schemas';





/**
 * @summary Create Db And Tables
 */
export const createDbAndTablesApiDevCreateDbAndTablesPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/dev/create-db-and-tables`,undefined,options
    );
  }



export const getCreateDbAndTablesApiDevCreateDbAndTablesPostMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDbAndTablesApiDevCreateDbAndTablesPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createDbAndTablesApiDevCreateDbAndTablesPost>>, TError,void, TContext> => {

const mutationKey = ['createDbAndTablesApiDevCreateDbAndTablesPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDbAndTablesApiDevCreateDbAndTablesPost>>, void> = () => {
          

          return  createDbAndTablesApiDevCreateDbAndTablesPost(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDbAndTablesApiDevCreateDbAndTablesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDbAndTablesApiDevCreateDbAndTablesPost>>>
    
    export type CreateDbAndTablesApiDevCreateDbAndTablesPostMutationError = AxiosError<unknown>

    /**
 * @summary Create Db And Tables
 */
export const useCreateDbAndTablesApiDevCreateDbAndTablesPost = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDbAndTablesApiDevCreateDbAndTablesPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDbAndTablesApiDevCreateDbAndTablesPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateDbAndTablesApiDevCreateDbAndTablesPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get Workers
 */
export const getWorkers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<WorkerResponse[]>> => {
    
    
    return axios.default.get(
      `/api/workers/`,options
    );
  }


export const getGetWorkersQueryKey = () => {
    return [`/api/workers/`] as const;
    }

    
export const getGetWorkersQueryOptions = <TData = Awaited<ReturnType<typeof getWorkers>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkers>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkers>>> = ({ signal }) => getWorkers({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkersQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkers>>>
export type GetWorkersQueryError = AxiosError<unknown>


export function useGetWorkers<TData = Awaited<ReturnType<typeof getWorkers>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkers>>,
          TError,
          Awaited<ReturnType<typeof getWorkers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkers<TData = Awaited<ReturnType<typeof getWorkers>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkers>>,
          TError,
          Awaited<ReturnType<typeof getWorkers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkers<TData = Awaited<ReturnType<typeof getWorkers>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Workers
 */

export function useGetWorkers<TData = Awaited<ReturnType<typeof getWorkers>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkersQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Worker
 */
export const createWorker = (
    workerCreate: WorkerCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<WorkerResponse>> => {
    
    
    return axios.default.post(
      `/api/workers/`,
      workerCreate,options
    );
  }



export const getCreateWorkerMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorker>>, TError,{data: WorkerCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createWorker>>, TError,{data: WorkerCreate}, TContext> => {

const mutationKey = ['createWorker'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorker>>, {data: WorkerCreate}> = (props) => {
          const {data} = props ?? {};

          return  createWorker(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWorkerMutationResult = NonNullable<Awaited<ReturnType<typeof createWorker>>>
    export type CreateWorkerMutationBody = WorkerCreate
    export type CreateWorkerMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Worker
 */
export const useCreateWorker = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorker>>, TError,{data: WorkerCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWorker>>,
        TError,
        {data: WorkerCreate},
        TContext
      > => {

      const mutationOptions = getCreateWorkerMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
