/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
export interface ClientCreate {
  name: string;
  score: number;
  create_at?: string;
  updated_at?: string;
}

export interface ClientResponse {
  name: string;
  score: number;
  create_at?: string;
  updated_at?: string;
  id: number;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ProjectCreateClientId = number | null;

export type ProjectCreateWorkerId = number | null;

export interface ProjectCreate {
  name: string;
  client_id?: ProjectCreateClientId;
  worker_id?: ProjectCreateWorkerId;
  created_at?: string;
  updated_at?: string;
}

export type ProjectResponseClientId = number | null;

export type ProjectResponseWorkerId = number | null;

export interface ProjectResponse {
  name: string;
  client_id?: ProjectResponseClientId;
  worker_id?: ProjectResponseWorkerId;
  created_at?: string;
  updated_at?: string;
  id: number;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface WorkerCreate {
  name: string;
  parental_surname: string;
  maternal_surname: string;
  created_at?: string;
  updated_at?: string;
}

export interface WorkerResponse {
  name: string;
  parental_surname: string;
  maternal_surname: string;
  created_at?: string;
  updated_at?: string;
  id: number;
}

export type WorkerUpdateName = string | null;

export type WorkerUpdateParentalSurname = string | null;

export type WorkerUpdateMaternalSurname = string | null;

export interface WorkerUpdate {
  name?: WorkerUpdateName;
  parental_surname?: WorkerUpdateParentalSurname;
  maternal_surname?: WorkerUpdateMaternalSurname;
}

